/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.lexer;

@SuppressWarnings("serial")
public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}
