/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.lexer;

import java.io.IOException;
import java.io.PushbackReader;
import java.io.Reader;

import ua.kiev.kpi.sc.parser.node.EOF;
import ua.kiev.kpi.sc.parser.node.TAmpAmp;
import ua.kiev.kpi.sc.parser.node.TAssign;
import ua.kiev.kpi.sc.parser.node.TBarBar;
import ua.kiev.kpi.sc.parser.node.TBoolean;
import ua.kiev.kpi.sc.parser.node.TChar;
import ua.kiev.kpi.sc.parser.node.TClassToken;
import ua.kiev.kpi.sc.parser.node.TComma;
import ua.kiev.kpi.sc.parser.node.TDot;
import ua.kiev.kpi.sc.parser.node.TDoubleQuote;
import ua.kiev.kpi.sc.parser.node.TElse;
import ua.kiev.kpi.sc.parser.node.TEmark;
import ua.kiev.kpi.sc.parser.node.TEq;
import ua.kiev.kpi.sc.parser.node.TFinal;
import ua.kiev.kpi.sc.parser.node.TFloat;
import ua.kiev.kpi.sc.parser.node.TFor;
import ua.kiev.kpi.sc.parser.node.TGt;
import ua.kiev.kpi.sc.parser.node.TGteq;
import ua.kiev.kpi.sc.parser.node.TIdentifier;
import ua.kiev.kpi.sc.parser.node.TIf;
import ua.kiev.kpi.sc.parser.node.TInt;
import ua.kiev.kpi.sc.parser.node.TLBkt;
import ua.kiev.kpi.sc.parser.node.TLBrc;
import ua.kiev.kpi.sc.parser.node.TLPar;
import ua.kiev.kpi.sc.parser.node.TLiteralBoolean;
import ua.kiev.kpi.sc.parser.node.TLiteralNull;
import ua.kiev.kpi.sc.parser.node.TLt;
import ua.kiev.kpi.sc.parser.node.TLteq;
import ua.kiev.kpi.sc.parser.node.TMinus;
import ua.kiev.kpi.sc.parser.node.TNeq;
import ua.kiev.kpi.sc.parser.node.TNew;
import ua.kiev.kpi.sc.parser.node.TNonNegativeInteger;
import ua.kiev.kpi.sc.parser.node.TPercent;
import ua.kiev.kpi.sc.parser.node.TPlus;
import ua.kiev.kpi.sc.parser.node.TPublic;
import ua.kiev.kpi.sc.parser.node.TRBkt;
import ua.kiev.kpi.sc.parser.node.TRBrc;
import ua.kiev.kpi.sc.parser.node.TRPar;
import ua.kiev.kpi.sc.parser.node.TReturn;
import ua.kiev.kpi.sc.parser.node.TSemi;
import ua.kiev.kpi.sc.parser.node.TShort;
import ua.kiev.kpi.sc.parser.node.TSlash;
import ua.kiev.kpi.sc.parser.node.TStar;
import ua.kiev.kpi.sc.parser.node.TStatic;
import ua.kiev.kpi.sc.parser.node.TStringToken;
import ua.kiev.kpi.sc.parser.node.TVoid;
import ua.kiev.kpi.sc.parser.node.TWhile;
import ua.kiev.kpi.sc.parser.node.TWhitespace;
import ua.kiev.kpi.sc.parser.node.Token;

@SuppressWarnings({"nls", "hiding"})
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

	public static String run(Reader in) {
		try {
			StringBuilder b = new StringBuilder();
			Lexer lexer = new Lexer(new PushbackReader(in, 1024));
	
			Token t = null;
	
			do {
				t = lexer.next();
				b.append(convertToken(t));
				b.append("\n");
			} while (!(t instanceof EOF));
			return b.toString();
		} catch (Exception ex){
			throw new RuntimeException(ex);
		}
	}
	

	private static String convertToken(Token t) {
		String nodeText = t.getText();
		nodeText = nodeText.replace("\n", "\\n");
		nodeText = nodeText.replace("\t", "\\t");
		nodeText = nodeText.replace("\r", "\\r");

		String res = String.format("[%1$3s, %2$3s]    %3$-15s %4$s", t
				.getLine(), t.getPos(), t.getClass().getSimpleName(), nodeText);
		return res;
	}
    
    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBkt(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrc(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBkt(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrc(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemi(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoubleQuote(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAmpAmp(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBarBar(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEmark(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEq(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGteq(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLt(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLteq(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNeq(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPercent(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSlash(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStar(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolean(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClassToken(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFinal(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloat(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNew(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPublic(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShort(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStatic(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVoid(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStringToken(line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLiteralBoolean(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLiteralNull(line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhitespace(text, line, pos); }
    Token new44(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new45(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNonNegativeInteger(text, line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChar(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable = 
    {
        { // INITIAL
            {{0, 32, 1}, {33, 33, 2}, {34, 34, 3}, {35, 36, 4}, {37, 37, 5}, {38, 38, 6}, {39, 39, 4}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {58, 58, 4}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {62, 62, 19}, {63, 64, 4}, {65, 82, 20}, {83, 83, 21}, {84, 90, 20}, {91, 91, 22}, {92, 92, 4}, {93, 93, 23}, {94, 96, 4}, {97, 97, 24}, {98, 98, 25}, {99, 99, 26}, {100, 100, 24}, {101, 101, 27}, {102, 102, 28}, {103, 104, 24}, {105, 105, 29}, {106, 109, 24}, {110, 110, 30}, {111, 111, 24}, {112, 112, 31}, {113, 113, 24}, {114, 114, 32}, {115, 115, 33}, {116, 116, 34}, {117, 117, 24}, {118, 118, 35}, {119, 119, 36}, {120, 122, 24}, {123, 123, 37}, {124, 124, 38}, {125, 125, 39}, {126, 65535, 4}, },
            {{0, 32, 40}, },
            {{61, 61, 41}, },
            {},
            {},
            {},
            {{38, 38, 42}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 43}, },
            {},
            {{61, 61, 44}, },
            {{61, 61, 45}, },
            {{61, 61, 46}, },
            {{65, 90, 47}, {97, 122, 48}, },
            {{65, 90, 47}, {97, 115, 48}, {116, 116, 49}, {117, 122, 48}, },
            {},
            {},
            {{65, 122, -22}, },
            {{65, 90, 47}, {97, 110, 48}, {111, 111, 50}, {112, 122, 48}, },
            {{65, 90, 47}, {97, 107, 48}, {108, 108, 51}, {109, 122, 48}, },
            {{65, 107, -28}, {108, 108, 52}, {109, 122, 48}, },
            {{65, 90, 47}, {97, 97, 53}, {98, 104, 48}, {105, 105, 54}, {106, 107, 48}, {108, 108, 55}, {109, 110, 48}, {111, 111, 56}, {112, 122, 48}, },
            {{65, 90, 47}, {97, 101, 48}, {102, 102, 57}, {103, 109, 48}, {110, 110, 58}, {111, 122, 48}, },
            {{65, 90, 47}, {97, 100, 48}, {101, 101, 59}, {102, 116, 48}, {117, 117, 60}, {118, 122, 48}, },
            {{65, 90, 47}, {97, 116, 48}, {117, 117, 61}, {118, 122, 48}, },
            {{65, 100, -32}, {101, 101, 62}, {102, 122, 48}, },
            {{65, 90, 47}, {97, 103, 48}, {104, 104, 63}, {105, 115, 48}, {116, 116, 64}, {117, 122, 48}, },
            {{65, 90, 47}, {97, 113, 48}, {114, 114, 65}, {115, 122, 48}, },
            {{65, 110, -27}, {111, 111, 66}, {112, 122, 48}, },
            {{65, 103, -35}, {104, 104, 67}, {105, 122, 48}, },
            {},
            {{124, 124, 68}, },
            {},
            {{0, 32, 40}, },
            {},
            {},
            {{48, 57, 43}, },
            {},
            {},
            {},
            {{65, 122, -22}, },
            {{65, 122, -22}, },
            {{65, 113, -36}, {114, 114, 69}, {115, 122, 48}, },
            {{65, 110, -27}, {111, 111, 70}, {112, 122, 48}, },
            {{65, 90, 47}, {97, 97, 71}, {98, 122, 48}, },
            {{65, 90, 47}, {97, 114, 48}, {115, 115, 72}, {116, 122, 48}, },
            {{65, 107, -28}, {108, 108, 73}, {109, 122, 48}, },
            {{65, 90, 47}, {97, 109, 48}, {110, 110, 74}, {111, 122, 48}, },
            {{65, 110, -27}, {111, 111, 75}, {112, 122, 48}, },
            {{65, 113, -36}, {114, 114, 76}, {115, 122, 48}, },
            {{65, 122, -22}, },
            {{65, 115, -23}, {116, 116, 77}, {117, 122, 48}, },
            {{65, 90, 47}, {97, 118, 48}, {119, 119, 78}, {120, 122, 48}, },
            {{65, 107, -28}, {108, 108, 79}, {109, 122, 48}, },
            {{65, 90, 47}, {97, 97, 48}, {98, 98, 80}, {99, 122, 48}, },
            {{65, 115, -23}, {116, 116, 81}, {117, 122, 48}, },
            {{65, 110, -27}, {111, 111, 82}, {112, 122, 48}, },
            {{65, 90, 47}, {97, 97, 83}, {98, 122, 48}, },
            {{65, 116, -33}, {117, 117, 84}, {118, 122, 48}, },
            {{65, 90, 47}, {97, 104, 48}, {105, 105, 85}, {106, 122, 48}, },
            {{65, 104, -68}, {105, 105, 86}, {106, 122, 48}, },
            {},
            {{65, 104, -68}, {105, 105, 87}, {106, 122, 48}, },
            {{65, 107, -28}, {108, 108, 88}, {109, 122, 48}, },
            {{65, 114, -54}, {115, 115, 89}, {116, 122, 48}, },
            {{65, 100, -32}, {101, 101, 90}, {102, 122, 48}, },
            {{65, 114, -54}, {115, 115, 91}, {116, 122, 48}, },
            {{65, 90, 47}, {97, 97, 92}, {98, 122, 48}, },
            {{65, 90, 47}, {97, 97, 93}, {98, 122, 48}, },
            {{65, 122, -22}, },
            {{65, 122, -22}, },
            {{65, 122, -22}, },
            {{65, 107, -28}, {108, 108, 94}, {109, 122, 48}, },
            {{65, 107, -28}, {108, 108, 95}, {109, 122, 48}, },
            {{65, 116, -33}, {117, 117, 96}, {118, 122, 48}, },
            {{65, 113, -36}, {114, 114, 97}, {115, 122, 48}, },
            {{65, 115, -23}, {116, 116, 98}, {117, 122, 48}, },
            {{65, 100, -32}, {101, 101, 99}, {102, 122, 48}, },
            {{65, 90, 47}, {97, 99, 48}, {100, 100, 100}, {101, 122, 48}, },
            {{65, 107, -28}, {108, 108, 101}, {109, 122, 48}, },
            {{65, 109, -56}, {110, 110, 102}, {111, 122, 48}, },
            {{65, 100, -32}, {101, 101, 103}, {102, 122, 48}, },
            {{65, 114, -54}, {115, 115, 104}, {116, 122, 48}, },
            {{65, 122, -22}, },
            {{65, 100, -32}, {101, 101, 105}, {102, 122, 48}, },
            {{65, 107, -28}, {108, 108, 106}, {109, 122, 48}, },
            {{65, 115, -23}, {116, 116, 107}, {117, 122, 48}, },
            {{65, 122, -22}, },
            {{65, 104, -68}, {105, 105, 108}, {106, 122, 48}, },
            {{65, 113, -36}, {114, 114, 109}, {115, 122, 48}, },
            {{65, 115, -23}, {116, 116, 110}, {117, 122, 48}, },
            {{65, 104, -68}, {105, 105, 111}, {106, 122, 48}, },
            {{65, 122, -22}, },
            {{65, 122, -22}, },
            {{65, 100, -32}, {101, 101, 112}, {102, 122, 48}, },
            {{65, 90, 47}, {97, 102, 48}, {103, 103, 113}, {104, 122, 48}, },
            {{65, 90, 47}, {97, 97, 114}, {98, 122, 48}, },
            {{65, 122, -22}, },
            {{65, 122, -22}, },
            {{65, 122, -22}, },
            {{65, 122, -22}, },
            {{65, 90, 47}, {97, 98, 48}, {99, 99, 115}, {100, 122, 48}, },
            {{65, 109, -56}, {110, 110, 116}, {111, 122, 48}, },
            {{65, 122, -22}, },
            {{65, 98, -110}, {99, 99, 117}, {100, 122, 48}, },
            {{65, 122, -22}, },
            {{65, 122, -22}, },
            {{65, 109, -56}, {110, 110, 118}, {111, 122, 48}, },
            {{65, 122, -22}, },
            {{65, 122, -22}, },
            {{65, 122, -22}, },
            {{65, 122, -22}, },
        }
    };

    private static int[][] accept = 
   {
        // INITIAL
        {44, 43, 13, 9, 46, 21, 46, 4, 7, 24, 22, 0, 19, 1, 23, 45, 8, 17, 11, 15, 44, 44, 2, 5, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 3, 46, 6, 43, 20, 10, 45, 18, 14, 16, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 31, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 12, 44, 44, 44, 44, 44, 44, 44, 30, 32, 33, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 27, 44, 44, 44, 42, 44, 44, 44, 44, 41, 38, 44, 44, 44, 26, 41, 28, 29, 44, 44, 36, 44, 39, 40, 44, 34, 35, 37, 25, },

    };

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    /*static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }*/
}
