/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class AConstantClassBodyElem extends PClassBodyElem
{
    private PConstantDefinition _constantDefinition_;
    private TSemi _semi_;

    public AConstantClassBodyElem()
    {
        // Constructor
    }

    public AConstantClassBodyElem(
        @SuppressWarnings("hiding") PConstantDefinition _constantDefinition_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setConstantDefinition(_constantDefinition_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AConstantClassBodyElem(
            cloneNode(this._constantDefinition_),
            cloneNode(this._semi_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstantClassBodyElem(this);
    }

    public PConstantDefinition getConstantDefinition()
    {
        return this._constantDefinition_;
    }

    public void setConstantDefinition(PConstantDefinition node)
    {
        if(this._constantDefinition_ != null)
        {
            this._constantDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constantDefinition_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._constantDefinition_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._constantDefinition_ == child)
        {
            this._constantDefinition_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._constantDefinition_ == oldChild)
        {
            setConstantDefinition((PConstantDefinition) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
