/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class AGtComparisonExpression extends PComparisonExpression
{
    private PSimpleExpression _simpleExpression_;
    private TGt _gt_;
    private PComparisonExpression _comparisonExpression_;

    public AGtComparisonExpression()
    {
        // Constructor
    }

    public AGtComparisonExpression(
        @SuppressWarnings("hiding") PSimpleExpression _simpleExpression_,
        @SuppressWarnings("hiding") TGt _gt_,
        @SuppressWarnings("hiding") PComparisonExpression _comparisonExpression_)
    {
        // Constructor
        setSimpleExpression(_simpleExpression_);

        setGt(_gt_);

        setComparisonExpression(_comparisonExpression_);

    }

    @Override
    public Object clone()
    {
        return new AGtComparisonExpression(
            cloneNode(this._simpleExpression_),
            cloneNode(this._gt_),
            cloneNode(this._comparisonExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGtComparisonExpression(this);
    }

    public PSimpleExpression getSimpleExpression()
    {
        return this._simpleExpression_;
    }

    public void setSimpleExpression(PSimpleExpression node)
    {
        if(this._simpleExpression_ != null)
        {
            this._simpleExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleExpression_ = node;
    }

    public TGt getGt()
    {
        return this._gt_;
    }

    public void setGt(TGt node)
    {
        if(this._gt_ != null)
        {
            this._gt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gt_ = node;
    }

    public PComparisonExpression getComparisonExpression()
    {
        return this._comparisonExpression_;
    }

    public void setComparisonExpression(PComparisonExpression node)
    {
        if(this._comparisonExpression_ != null)
        {
            this._comparisonExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparisonExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleExpression_)
            + toString(this._gt_)
            + toString(this._comparisonExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleExpression_ == child)
        {
            this._simpleExpression_ = null;
            return;
        }

        if(this._gt_ == child)
        {
            this._gt_ = null;
            return;
        }

        if(this._comparisonExpression_ == child)
        {
            this._comparisonExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleExpression_ == oldChild)
        {
            setSimpleExpression((PSimpleExpression) newChild);
            return;
        }

        if(this._gt_ == oldChild)
        {
            setGt((TGt) newChild);
            return;
        }

        if(this._comparisonExpression_ == oldChild)
        {
            setComparisonExpression((PComparisonExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
