/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleFactArgList extends PFactArgList
{
    private PExpression _expression_;
    private TComma _comma_;
    private PFactArgList _factArgList_;

    public AMultipleFactArgList()
    {
        // Constructor
    }

    public AMultipleFactArgList(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PFactArgList _factArgList_)
    {
        // Constructor
        setExpression(_expression_);

        setComma(_comma_);

        setFactArgList(_factArgList_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleFactArgList(
            cloneNode(this._expression_),
            cloneNode(this._comma_),
            cloneNode(this._factArgList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleFactArgList(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PFactArgList getFactArgList()
    {
        return this._factArgList_;
    }

    public void setFactArgList(PFactArgList node)
    {
        if(this._factArgList_ != null)
        {
            this._factArgList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factArgList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._comma_)
            + toString(this._factArgList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._factArgList_ == child)
        {
            this._factArgList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._factArgList_ == oldChild)
        {
            setFactArgList((PFactArgList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
