/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleNVarFormalArgList extends PFormalArgList
{
    private PVariableDefinition _variableDefinition_;

    public AMultipleNVarFormalArgList()
    {
        // Constructor
    }

    public AMultipleNVarFormalArgList(
        @SuppressWarnings("hiding") PVariableDefinition _variableDefinition_)
    {
        // Constructor
        setVariableDefinition(_variableDefinition_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleNVarFormalArgList(
            cloneNode(this._variableDefinition_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleNVarFormalArgList(this);
    }

    public PVariableDefinition getVariableDefinition()
    {
        return this._variableDefinition_;
    }

    public void setVariableDefinition(PVariableDefinition node)
    {
        if(this._variableDefinition_ != null)
        {
            this._variableDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variableDefinition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variableDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variableDefinition_ == child)
        {
            this._variableDefinition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variableDefinition_ == oldChild)
        {
            setVariableDefinition((PVariableDefinition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
