/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class ANothingFormalArgList extends PFormalArgList
{

    public ANothingFormalArgList()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ANothingFormalArgList();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANothingFormalArgList(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
