/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleSimpleExpression extends PSimpleExpression
{
    private PSummand _summand_;

    public ASimpleSimpleExpression()
    {
        // Constructor
    }

    public ASimpleSimpleExpression(
        @SuppressWarnings("hiding") PSummand _summand_)
    {
        // Constructor
        setSummand(_summand_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleSimpleExpression(
            cloneNode(this._summand_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleSimpleExpression(this);
    }

    public PSummand getSummand()
    {
        return this._summand_;
    }

    public void setSummand(PSummand node)
    {
        if(this._summand_ != null)
        {
            this._summand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._summand_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._summand_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._summand_ == child)
        {
            this._summand_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._summand_ == oldChild)
        {
            setSummand((PSummand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
