/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class TLiteralNull extends Token
{
    public TLiteralNull()
    {
        super.setText("null");
    }

    public TLiteralNull(int line, int pos)
    {
        super.setText("null");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLiteralNull(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLiteralNull(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLiteralNull text.");
    }
}
