/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class AEqOperandAnd extends POperandAnd
{
    private PComparisonExpression _comparisonExpression_;
    private TEq _eq_;
    private POperandAnd _operandAnd_;

    public AEqOperandAnd()
    {
        // Constructor
    }

    public AEqOperandAnd(
        @SuppressWarnings("hiding") PComparisonExpression _comparisonExpression_,
        @SuppressWarnings("hiding") TEq _eq_,
        @SuppressWarnings("hiding") POperandAnd _operandAnd_)
    {
        // Constructor
        setComparisonExpression(_comparisonExpression_);

        setEq(_eq_);

        setOperandAnd(_operandAnd_);

    }

    @Override
    public Object clone()
    {
        return new AEqOperandAnd(
            cloneNode(this._comparisonExpression_),
            cloneNode(this._eq_),
            cloneNode(this._operandAnd_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqOperandAnd(this);
    }

    public PComparisonExpression getComparisonExpression()
    {
        return this._comparisonExpression_;
    }

    public void setComparisonExpression(PComparisonExpression node)
    {
        if(this._comparisonExpression_ != null)
        {
            this._comparisonExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparisonExpression_ = node;
    }

    public TEq getEq()
    {
        return this._eq_;
    }

    public void setEq(TEq node)
    {
        if(this._eq_ != null)
        {
            this._eq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eq_ = node;
    }

    public POperandAnd getOperandAnd()
    {
        return this._operandAnd_;
    }

    public void setOperandAnd(POperandAnd node)
    {
        if(this._operandAnd_ != null)
        {
            this._operandAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operandAnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comparisonExpression_)
            + toString(this._eq_)
            + toString(this._operandAnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comparisonExpression_ == child)
        {
            this._comparisonExpression_ = null;
            return;
        }

        if(this._eq_ == child)
        {
            this._eq_ = null;
            return;
        }

        if(this._operandAnd_ == child)
        {
            this._operandAnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comparisonExpression_ == oldChild)
        {
            setComparisonExpression((PComparisonExpression) newChild);
            return;
        }

        if(this._eq_ == oldChild)
        {
            setEq((TEq) newChild);
            return;
        }

        if(this._operandAnd_ == oldChild)
        {
            setOperandAnd((POperandAnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
