/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class AMultiClassSeq extends PClassSeq
{
    private PNotPublicClass _notPublicClass_;
    private PClassSeq _classSeq_;

    public AMultiClassSeq()
    {
        // Constructor
    }

    public AMultiClassSeq(
        @SuppressWarnings("hiding") PNotPublicClass _notPublicClass_,
        @SuppressWarnings("hiding") PClassSeq _classSeq_)
    {
        // Constructor
        setNotPublicClass(_notPublicClass_);

        setClassSeq(_classSeq_);

    }

    @Override
    public Object clone()
    {
        return new AMultiClassSeq(
            cloneNode(this._notPublicClass_),
            cloneNode(this._classSeq_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiClassSeq(this);
    }

    public PNotPublicClass getNotPublicClass()
    {
        return this._notPublicClass_;
    }

    public void setNotPublicClass(PNotPublicClass node)
    {
        if(this._notPublicClass_ != null)
        {
            this._notPublicClass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notPublicClass_ = node;
    }

    public PClassSeq getClassSeq()
    {
        return this._classSeq_;
    }

    public void setClassSeq(PClassSeq node)
    {
        if(this._classSeq_ != null)
        {
            this._classSeq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classSeq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._notPublicClass_)
            + toString(this._classSeq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._notPublicClass_ == child)
        {
            this._notPublicClass_ = null;
            return;
        }

        if(this._classSeq_ == child)
        {
            this._classSeq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._notPublicClass_ == oldChild)
        {
            setNotPublicClass((PNotPublicClass) newChild);
            return;
        }

        if(this._classSeq_ == oldChild)
        {
            setClassSeq((PClassSeq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
