/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleOperandOr extends POperandOr
{
    private POperandAnd _operandAnd_;

    public ASimpleOperandOr()
    {
        // Constructor
    }

    public ASimpleOperandOr(
        @SuppressWarnings("hiding") POperandAnd _operandAnd_)
    {
        // Constructor
        setOperandAnd(_operandAnd_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleOperandOr(
            cloneNode(this._operandAnd_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleOperandOr(this);
    }

    public POperandAnd getOperandAnd()
    {
        return this._operandAnd_;
    }

    public void setOperandAnd(POperandAnd node)
    {
        if(this._operandAnd_ != null)
        {
            this._operandAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operandAnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._operandAnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._operandAnd_ == child)
        {
            this._operandAnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._operandAnd_ == oldChild)
        {
            setOperandAnd((POperandAnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
