/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleInteger extends PInteger
{
    private TNonNegativeInteger _nonNegativeInteger_;

    public ASimpleInteger()
    {
        // Constructor
    }

    public ASimpleInteger(
        @SuppressWarnings("hiding") TNonNegativeInteger _nonNegativeInteger_)
    {
        // Constructor
        setNonNegativeInteger(_nonNegativeInteger_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleInteger(
            cloneNode(this._nonNegativeInteger_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleInteger(this);
    }

    public TNonNegativeInteger getNonNegativeInteger()
    {
        return this._nonNegativeInteger_;
    }

    public void setNonNegativeInteger(TNonNegativeInteger node)
    {
        if(this._nonNegativeInteger_ != null)
        {
            this._nonNegativeInteger_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nonNegativeInteger_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nonNegativeInteger_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nonNegativeInteger_ == child)
        {
            this._nonNegativeInteger_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nonNegativeInteger_ == oldChild)
        {
            setNonNegativeInteger((TNonNegativeInteger) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
