/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleSummand extends PSummand
{
    private PMultiplier _multiplier_;

    public ASimpleSummand()
    {
        // Constructor
    }

    public ASimpleSummand(
        @SuppressWarnings("hiding") PMultiplier _multiplier_)
    {
        // Constructor
        setMultiplier(_multiplier_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleSummand(
            cloneNode(this._multiplier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleSummand(this);
    }

    public PMultiplier getMultiplier()
    {
        return this._multiplier_;
    }

    public void setMultiplier(PMultiplier node)
    {
        if(this._multiplier_ != null)
        {
            this._multiplier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multiplier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multiplier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multiplier_ == child)
        {
            this._multiplier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multiplier_ == oldChild)
        {
            setMultiplier((PMultiplier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
