/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASingleCompilationUnit extends PCompilationUnit
{
    private PPublicClass _publicClass_;

    public ASingleCompilationUnit()
    {
        // Constructor
    }

    public ASingleCompilationUnit(
        @SuppressWarnings("hiding") PPublicClass _publicClass_)
    {
        // Constructor
        setPublicClass(_publicClass_);

    }

    @Override
    public Object clone()
    {
        return new ASingleCompilationUnit(
            cloneNode(this._publicClass_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleCompilationUnit(this);
    }

    public PPublicClass getPublicClass()
    {
        return this._publicClass_;
    }

    public void setPublicClass(PPublicClass node)
    {
        if(this._publicClass_ != null)
        {
            this._publicClass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._publicClass_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._publicClass_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._publicClass_ == child)
        {
            this._publicClass_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._publicClass_ == oldChild)
        {
            setPublicClass((PPublicClass) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
