/* This file was generated by SableCC (http://www.sablecc.org/). */

package ua.kiev.kpi.sc.parser.node;

import java.util.*;
import ua.kiev.kpi.sc.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASingleBlock extends PBlock
{
    private final LinkedList<POperator> _operator_ = new LinkedList<POperator>();

    public ASingleBlock()
    {
        // Constructor
    }

    public ASingleBlock(
        @SuppressWarnings("hiding") List<POperator> _operator_)
    {
        // Constructor
        setOperator(_operator_);

    }

    @Override
    public Object clone()
    {
        return new ASingleBlock(
            cloneList(this._operator_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleBlock(this);
    }

    public LinkedList<POperator> getOperator()
    {
        return this._operator_;
    }

    public void setOperator(List<POperator> list)
    {
        this._operator_.clear();
        this._operator_.addAll(list);
        for(POperator e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._operator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._operator_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<POperator> i = this._operator_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((POperator) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
